services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bookstore_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: BookStore.Api/Dockerfile
    container_name: bookstore_api
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=BookStoreDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;
    depends_on:
      - db

volumes:
  sql_data: